name: Hello World!

on:
  schedule:
    - cron: "* * * * *"
jobs:
    hello-world:
        runs-on: ubuntu-22.04
        container:
            image: rkrispin/data-pipeline-automation-with-github-actions:prod
        steps:
            - name: print-hello-world
              run: echo "Hello World!"
